### PR TITLE
Expose user token in API

### PR DESCRIPTION
**Pull request by thegecko**
Rather than exposing 'accessTokenKey' and 'accessTokenService' for something like `keytar` to use, expose the apiToken directly.

### CODE REVIEW

**Review by mcgordonite — COMMENTED** [review]
The token may change during the lifetime of the plugin if the user logs out, or if we need to use the refresh token.

Is the assumption that the config will remain the same for the lifetime of the plugin, or should plugins call `getConfig` every time they need it? Maybe this should be a separate function for retrieving the token instead.

**Comment by thegecko** [comment]
> The token may change during the lifetime of the plugin if the user logs out

This scenario isn't currently supported, so perhaps out of scope / seperate issue.

> Is the assumption that the config will remain the same for the lifetime of the plugin

That was my assumption, the online version would kill the session, not sure what happens on the desktop.

> Maybe this should be a separate function for retrieving the token instead.

I'm keen to avoid splitting the API to be too granular, ie lots of sections with a single call. But this could be changed to be:

```typescript
        export interface Config {
            customTargetType: string;   // String to use for identifying custom targets
            targetsApiUrl: string;      // URL of mbed targets API
        }

        export function getConfig(): Promise<Config>;

        export function getApiToken(): Promise<String | Undefined>;
```

(+1 Hour)

**Comment by mcgordonite** [comment]
@thegecko I like the suggestion of a separate `getApiToken`. Looks future-proof.

**Comment by thegecko** [comment]
Updated, ready for final review

**Review by mcgordonite — APPROVED** [review]

**Pull request merged**
